### PR TITLE
Scheduler now also garbage-collects VMs from weave-net-tests.

### PR DESCRIPTION
**Pull request by marccarre**
This is required so that VMs started by build-tools/provisioning against the weave-net-tests project in GCP are garbage collected, should an issue arise and therefore, should the VMs be kept up and running for no good reason.

This work is related to weaveworks/weave#2647 and weaveworks/build-tools#53.

### CODE REVIEW

**Comment by tomwilkie** [comment]
LGTM

**Comment by marccarre** [comment]
N.B.: manually tested the snippets from the change in a REPL, since we don't have unit / integration tests for this script.

```
$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> NAME_REGEXES = [
...   re.compile(r'^host(?P<index>\d+)-(?P<build>\d+)-(?P<shard>\d+)$'),
...   re.compile(r'^test-(?P<build>\d+)-(?P<shard>\d+)-(?P<index>\d+)$'),
... ]
>>> 
>>> 
>>> def _matches_any_regex(name):
...   for regex in NAME_REGEXES:
...     matches = regex.match(name)
...     if matches:
...       return matches
... 
>>> bool(_matches_any_regex('blah'))
False
>>> bool(_matches_any_regex('test-0-11-12'))
True
>>> bool(_matches_any_regex('te-0-11-12'))
False
>>> bool(_matches_any_regex('host0-11-12'))
True
>>> bool(_matches_any_regex('host-0-11-12'))
False
```

**Comment by marccarre** [comment]
Deployed -- currently keeping an eye on it in AppEngine:

```
$ appcfg.py update .
04:13 PM Application: positive-cocoa-90213; version: 1
04:13 PM Host: appengine.google.com
04:13 PM Starting update of app: positive-cocoa-90213, version: 1
04:13 PM Getting current resource limits.
04:13 PM Scanning files on local disk.
04:13 PM Cloning 393 application files.
04:13 PM Uploading 7 files and blobs.
04:13 PM Uploaded 7 files and blobs.
04:13 PM Compilation starting.
04:13 PM Compilation completed.
04:13 PM Starting deployment.
04:13 PM Checking if deployment succeeded.
04:13 PM Deployment successful.
04:13 PM Checking if updated app version is serving.
04:13 PM Completed update of app: positive-cocoa-90213, version: 1
04:13 PM Uploading cron entries.
```

**Comment by marccarre** [comment]
Confirmed it is working as expected (and VM does get deleted):

```
16:45:00.445
GCing weaveworks/weave, weave-net-tests, us-central1-a [...]
16:45:00.472
URL being requested: GET [...]
16:45:00.472
Attempting refresh to obtain initial access_token [...]
16:45:00.677
Running VMs by build: defaultdict(<type 'list'>, {123: [u'test-123-0-0']}) [...]
16:45:00.944
Runnings builds: set([]) [...]
16:45:01.360
Stopping VM test-123-0-0 [...]
16:45:01.443
URL being requested: DELETE [...]
```

**Pull request merged**
