### PR TITLE
Try and vendor a specific version of shfmt

### PR DESCRIPTION
**Pull request by tomwilkie**
Due to https://github.com/mvdan/sh/issues/47

### CODE REVIEW

**Comment by mvdan** [comment]
FWIW, you will run into little issues like these if you always run master. I've been tagging releases for a while now, you should use those and only bump version from time to time.

This problem in particular is a bug that shouldn't have happened, but other changes in the format or behaviour of the tool could be on purpose. And you don't want different devs to be on different versions of master.

**Comment by tomwilkie** [comment]
@mvdan you advise users in your read me to use `go get`, so you shouldn't be surprised when people use it and follow master..

**Comment by mvdan** [comment]
That's true. I'll try to fuzz more often.

**Comment by tomwilkie** [comment]
How long does the fuzzing take?  Have you considered using travisci or circleci for it?

**Comment by mvdan** [comment]
Fuzzing by design does not take any finite amount of time. You can fuzz for an hour and not find any new bug. Or you can fuzz for a minute and find a couple.

I've seen it suggested that `go-fuzz` should run as part of CI. But I haven't seen any project do it yet, not even Go itself which does use fuzzing internally from time to time.

I can think of ways to have fuzzing run for something like a minute on Travis at each commit, and make progress over time by keeping the corpus persistent between runs. But that would be a very complicated setup and it would still not guarantee proper fuzzing on every commit.

For the time being, I'm fuzzing properly after I make any substantial changes to the parser or printer that could lead to human error. And of course, I'm adding regression tests. This is what Go does too. The good news is that, over time, as more regression tests are added new hang/panic bugs should become less and less frequent.

Also - to clarify - running master is fine and it's supported. I will do my best to not break master nor make any further changes to the format. What I meant by running releases (or specific vendored commits like this) is that it can save you time if that's a priority.

I've been thinking about adding an example `.travis-ci.yml` which downloads the latest released binary, but haven't gotten around to it yet.

**Pull request merged**
