### PR TITLE
Fix linter warnings

### PR DESCRIPTION
**Pull request by schu**

### CODE REVIEW

**Comment by tomwilkie** [comment]
@schu you need to `go get gopkg.in/mvdan/sh.v1/cmd/shfmt` where you use built tools - `shfmt` is a bit of a moving target, and we've given up trying to keep up with tip.

**Comment by tomwilkie** [comment]
please stick a note in the build tools readme to this affect!

**Comment by schu** [comment]
@tomwilkie like 4bd58d3? `go get gopkg.in/mvdan/sh.v1/cmd/shfmt` currently installs version 1.1 which reports the warnings fixed with b5ee028

**Comment by 2opremio** [comment]
@schu Are you sure? this repository uses [`gopkg.in/mvdan/sh.v1/cmd/shfmt`](https://github.com/weaveworks/build-tools/blob/master/circle.yml#L22-L26) and the latest master doesn't show any problems: https://circleci.com/gh/weaveworks/build-tools/388

**Comment by schu** [comment]
@2opremio no, actually b5ee028 fixes warnings reported by shellcheck 0.4.4 (the version on my host) and not shfmt and I confused those. IIRC shellcheck is not available on Circle CI, so those warnings go unnoticed there. Version 0.3.4 reports only the SC2086 warning in `lint`.

Do you want me change or drop  b5ee028?

**Comment by 2opremio** [comment]
I would say let's leave them if they don't result in errors with `gopkg.in/mvdan/sh.v1/cmd/shfmt`

**Comment by schu** [comment]
> I would say let's leave them if they don't result in errors with `gopkg.in/mvdan/sh.v1/cmd/shfmt`

You mean leave the warnings in / drop the commit? We could not use `shell-lint` in tcptracer-bpf then - https://circleci.com/gh/kinvolk/tcptracer-bpf/340 - as the shellcheck version in Fedora 24 also reports on the errors.

**Comment by 2opremio** [comment]
@schu I see, then let's leave them (assuming it won't conflict with shellcheck in ubuntu). Can you confirm that?

**Comment by schu** [comment]
> leave them (assuming it won't conflict with shellcheck in ubuntu). Can you confirm that?

Tested on Xenial (shellcheck 0.3.7) and Trusty (trusty-backports shellcheck 0.3.3), works.

**Pull request merged**
