### PR TITLE
Add experimental support for user tokens

### PR DESCRIPTION
**Pull request by paulbellamy**
wcloud side of https://github.com/weaveworks/service/pull/815

### CODE REVIEW

**Comment by tomwilkie** [comment]
Given you're implementing the user tokens support, I'd drop the whole context thing (its not something we expect people to use going forward, right?).

I would therefor have a config file that contains the user token and default instance, and allow people to override instance on the command line.  WDYT?

**Comment by paulbellamy** [comment]
Yeah, that is also fine. Will close the context PR in favour of this.

Overriding on the CLI (with a flag) is tricky without moving to something like cobra (which is a pain).

**Comment by paulbellamy** [comment]
So, this either needs an endpoint that both probes and user tokens can access which lists the instances you have access to (like `/users/api/lookup`), or a way to differentiate the type of token supplied.

**Comment by tomwilkie** [comment]
> a way to differentiate the type of token supplied.

how about we leave the current probe tokens as a env var, and just treat all the tokens in the config as user tokens?

**Comment by tomwilkie** [comment]
(and deprecate the env vars)

**Comment by paulbellamy** [comment]
Could do, I wanted it to support either interchangeably, as there is still no (nice) way to create user api tokens. That way it would be a more seamless changeover when that is available.

Also, I was thinking it makes sense to support probe tokens in general, as they make more sense for some situations (e.g. deploy from circle).

**Comment by jml** [comment]
Maybe a prefix for the user api tokens, to disambiguate lexically?

**Comment by tomwilkie** [comment]
LGTM

**Pull request merged**
