### PR TITLE
Add wcloud instance (name) command and loading ~/.wcloudconfig

### PR DESCRIPTION
**Pull request by paulbellamy**

### CODE REVIEW

**Comment by tomwilkie** [comment]
Thanks, Paul!

I don't feel particularly strong about this, but some nits:
- I preferred instance to context.  Whats the rationale behind context?
- I don't like having the tool modify the config; this doesn't work well for kubectl as it looses all the formatting.  I'd prefer the config be static, have the ability to specify a default instance in the config, and pick a config on a per command basis (doing --instance=dev etc)

WDYT?

**Comment by paulbellamy** [comment]
Rationale is that instance is used to mean a different thing in cloud. Potentially, it just needs more thought on how wcloud interacts with different instances, and if you have access to multiple instances, etc...

**Comment by tomwilkie** [comment]
> Rationale is that instance is used to mean a different thing in cloud.

This was my confusion, because as this stands they do not mean different things.  But I guess with #41 they will, so context is fine.

**Comment by paulbellamy** [comment]
Closed in favour of https://github.com/weaveworks/build-tools/pull/41

**Pull request closed without merging**
