### PR TITLE
Give up on versioned copy of shfmt; it doesn't build

### PR DESCRIPTION
**Pull request by bboreham**
Not today, anyway.

### CODE REVIEW

**Comment by tomwilkie** [comment]
We used to use master shfmt but it was a moving target - every time we fetched it it would find new errors.  Which was annoying.

They make binary releases available, I suggest we switch to using one of them? https://github.com/mvdan/sh/releases

**Comment by tomwilkie** [comment]
Also, the build containers will all need updating: https://github.com/weaveworks/build-tools/blob/master/build/golang/Dockerfile#L32

**Comment by mvdan** [comment]
Oh, this seems to be because of how gopkg.in works... It rewrites the `cmd/shfmt` import path, but not the `syntax` one. So it tries to combine v1 of one with v2 of the other, which definitely won't build.

You could try manually building the tag 1.3.0 somehow, like with `go get -d`, `git checkout` and then `go install`.

**Comment by bboreham** [comment]
> Also, the build containers will all need updating: https://github.com/weaveworks/build-tools/blob/master/build/golang/Dockerfile#L32

I don't follow.  The line you pointed at is already using the head revision of shfmt.

What uses that file?

**Comment by marccarre** [comment]
FYI: I've implemented the workaround detailed by @mvdan successfully [here](https://github.com/mvdan/sh/issues/107#issuecomment-302698990).

**Comment by marccarre** [comment]
I took the liberty of overriding @bboreham's changes to harmonise the way we do this in: 
- `build-tools` (this PR, previous commits in `master`: 5cdba32, c322ca8, e59c225), 
- `weave` (weaveworks/weave/pull/2987)
- `cortex` (weaveworks/cortex/pull/434, weaveworks/cortex/pull/435)

@bboreham, @tomwilkie, PTAL.

**Comment by tomwilkie** [comment]
LGTM

**Pull request merged**
