### PR TITLE
Garbage-Collect firewall rules

### PR DESCRIPTION
**Pull request by bboreham**
Introduced by https://github.com/weaveworks/weave/pull/2670

(I haven't figured out how to test this yet)

### CODE REVIEW

**Comment by bboreham** [comment]
I realise this was done in ignorance of https://github.com/weaveworks/weave/pull/1895.
It seems like a complicated task to re-integrate the two forks.

**Comment by marccarre** [comment]
This may not work as expected, as the regex does not match `docker` in the names:

```
>>> import re
>>> FIRE_RE = re.compile(r'^(?P<network>\d+)-allow-(?P<type>\d+)-(?P<build>\d+)-(?P<shard>\d+)$')
False
```

Will fix and also add support for the testing MVP.

**Comment by marccarre** [comment]
Manual tests:

```
$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> def _matches_any_regex(name, regexes):
...   for regex in regexes:
...     matches = regex.match(name)
...     if matches:
...       return matches
... 
>>> FIREWALL_REGEXES = [
...   re.compile(r'^(?P<network>\w+)-allow-(?P<type>\w+)-(?P<build>\d+)-(?P<shard>\d+)$'),
...   re.compile(r'^(?P<network>\w+)-(?P<build>\d+)-(?P<shard>\d+)-allow-(?P<type>[\w\-]+)$'),
... ]
>>> 
>>> bool(_matches_any_regex('test-allow-docker-7374-1', FIREWALL_REGEXES))
True
>>> bool(_matches_any_regex('test-7664-0-allow-docker-and-weave', FIREWALL_REGEXES))
True
>>> bool(_matches_any_regex('test-allow-docker-dev-marc', FIREWALL_REGEXES))
False
>>> bool(_matches_any_regex('test-allow-docker-and-weave', FIREWALL_REGEXES))
False
```

**Comment by marccarre** [comment]
N.B.: I've purposedly left many individual commits for ease of review, but can squash them all as one commit once this gets LGTM'ed.

**Comment by tomwilkie** [comment]
LGTM!

**Comment by marccarre** [comment]
Added a flag to enable/disable GC of firewall rules.
Working as expected under GAE, and GC-ing unused firewall rules of both legacy and new Weave Net tests.

**Pull request merged**
