### PR TITLE
circleci: Also lint shell scripts

### PR DESCRIPTION
**Pull request by ekimekim**
see https://github.com/weaveworks/scope/pull/1776#issuecomment-238820963

### CODE REVIEW

**Comment by jml** [comment]
shellcheck isn't installed. (And you have to be sure you get the right version too!) In `service-conf`, we do this by running the linter in a docker image.

**Comment by ekimekim** [comment]
This seems like...a lot of work (new makefile, etc). I might see if I can get away with installing a version in the circleci vm, or just give up.

**Comment by tomwilkie** [comment]
> I might see if I can get away with installing a version in the circleci vm

I don't mind if you do this, but making a build container shouldn't be too much work, and is good practice.

**Comment by jml** [comment]
Please feel free re-assign to me when the tests pass.

**Comment by tomwilkie** [comment]
Looks like this has been superseded now.

**Pull request closed without merging**
